***Variables***

${main_title_BBVA_next}             BBVA Next Technologies | Unimos personas y tecnología
${blog}                             xpath=(//a[contains(.,'Blog')])[2]
${last_page}                        xpath=//span[contains(@class,'blog-pagination-control last-page')]
${penultimate_page}                 xpath=//a[contains(.,'12')]
${blog_post}                        xpath=(//h2[contains(@class,'post-title mb-3')])[8]
${title}                            Google Cloud Next ‘18: las claves del evento más importante de Google Cloud - BBVA Next Technologies